Algoritmo "exemplo esrutura de repetição composta"
// Disciplina  : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Luiza
// Data atual  : 05/09/2024
Var
   idade: inteiro


Inicio
   escreval("Digite sua idade")
   leia(idade)

   se idade < 18 entao
      escreval("Você é menor de 18")
   senao
      escreval("Você é maior de 18")
   fimse


Fimalgoritmo