Algoritmo "L05B"
// Disciplina  : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Luiza
// Data atual  : 17/09/2024
Var
cont, cont2:inteiro


Inicio
 para cont de 1 ate 10 passo 1 faca
 para cont2 de 1 ate 10 passo 1 faca
 escreval(cont, " X ", cont2, " =", cont*cont2)
 fimpara
 fimpara

Fimalgoritmo