Algoritmo "L05D"
// Disciplina  : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Luiza
// Data atual  : 17/09/2024
Var
cont, somador: inteiro


Inicio
para cont de 1 ate 500 passo 1 faca
se cont % 2 = 0 entao
somador <- somador + cont
fimse
fimpara

escreva(somador)


Fimalgoritmo