Algoritmo "Positivo ou negativo"
// Disciplina  : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : o programa vai pergar um valor e vai dizer se ele é positivo ou negativo
// Autor(a)    : Maria Luiza
// Data atual  : 05/09/2024
Var
   numero: inteiro


Inicio
   escreval("Digite um numero")
   leia(numero)

   se numero >= 0 entao
      escreval("O numero é positivo")
   senao
      escreval("O numero é negativo")
      fimse


Fimalgoritmo