Algoritmo "Soma de todos os numeros ate 100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : soma todos os numeros de 0 a 100
// Autor(a)    : Maria Luiza
// Data atual  : 09/09/2024
Var
// contadora, resultado
cont, resultado: inteiro

Inicio

enquanto cont <= 100 faca
resultado <- resultado + cont
cont <- cont + 1
fimenquanto

escreval("O valor da soma dos 100 primeiros números é de:", resultado)



Fimalgoritmo